# Site settings
title: Africa is Everywhere
author:
  name: Heidrun & Anthony Simm
  email: email@email.com
description: "Thoughts about Portugal."

# Build settings
remote_theme: jekyll/minima

markdown: kramdown
