# Site settings
title: Africa is Everywhere
author:
  name: Anthony Simm
  email: your-email@domain.com
description: "Great blog site about our arrival and insights at Portugal."

# Build settings
remote_theme: jekyll/minima
